name: flutter_starter
description: Flutter Starter.
publish_to: 'none'
version: 0.0.1
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  # UI
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  responsive_framework: ^0.2.0
  im_stepper: ^1.0.1+1
  image_picker: ^0.8.5+3
  flutter_picker: ^2.0.5
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.3
  dotted_border: ^2.0.0+2
  photo_view: ^0.14.0
  bot_toast: ^4.0.3
  scroll_to_index: ^3.0.1
  #State Management
  flutter_bloc: ^8.0.1
  provider: ^6.0.3

  #DI
  get_it: ^7.2.0
  injectable: ^1.5.3

  #Network and Data parse
  retrofit: ^3.0.1
  equatable: ^2.0.3
  copy_with_extension: ^4.0.2
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0

  #Storage
  drift: ^1.7.0
  flutter_secure_storage: ^5.0.2
  sqlite3_flutter_libs: ^0.5.0

  #Utils
  path_provider: ^2.0.0
  path: ^1.8.1
  connectivity_plus: ^2.3.4


dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^4.0.1
  copy_with_extension_gen: ^4.0.2
  injectable_generator: ^1.5.3
  drift_dev: ^1.7.0
  build: ^2.2.1
  bloc_test: ^9.0.3
  # mockito: ^5.2.0
  mocktail: ^0.3.0
  flutter_gen_runner:


dependency_overrides:
  analyzer: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - .env.int
    - .env.staging
    - .env.prod
    # Images
    - assets/images/
    - assets/svgs/
  fonts:
    - family: RalewayBold
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
    - family: RalewayMedium
      fonts:
          - asset: assets/fonts/Raleway-Medium.ttf
    - family: RalewayRegular
      fonts:
          - asset: assets/fonts/Raleway-Regular.ttf
    - family: RalewaySemiBold
      fonts:
          - asset: assets/fonts/Raleway-SemiBold.ttf
    - family: SourceSansProBold
      fonts:
          - asset: assets/fonts/SourceSansPro-Bold.otf
    - family: SourceSansProLight
      fonts:
          - asset: assets/fonts/SourceSansPro-Light.otf
    - family: SourceSansProRegular
      fonts:
          - asset: assets/fonts/SourceSansPro-Regular.otf