import 'package:drift/drift.dart';
import 'package:flutter_starter/platform/database/connection/connection.dart' as impl;
import 'package:flutter_starter/platform/database/daos/dao_list.dart';
import 'package:flutter_starter/platform/database/tables/sync_data.dart';
import 'package:flutter_starter/platform/database/tables/table_list.dart';
import 'package:injectable/injectable.dart';

// Generated by drift_dev when running `build_runner build`
part 'database.g.dart';

@Singleton()
@DriftDatabase(tables: TableList.allTable, daos: DaoList.allDao)
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super.connect(impl.connect());

  @override
  int get schemaVersion => 16;

  @override
  MigrationStrategy get migration {
    return MigrationStrategy(
      onCreate: (Migrator m) async {
        await m.createAll();
      },
      onUpgrade: ((migrate, from, to) async {
        //from: is the version we are currently running before upgrade
        // disable foreign_keys before migrations
        await customStatement('PRAGMA foreign_keys = OFF');
      }),
      beforeOpen: (details) async {
        // Make sure that foreign keys are enabled
        await customStatement('PRAGMA foreign_keys = ON');
      },
    );
  }
}
